---
- hosts: bastion
  become: yes

  tasks:
#  - name: "check if known_hosts contains server's fingerprint"
#    local_action: command ssh-keygen -F {{ inventory_hostname }}
#    register: keygen
#    failed_when: keygen.stderr != ''
#    changed_when: False

#  - name: fetch remote ssh key
#    local_action: command ssh-keyscan -T5 {{ inventory_hostname }}
#    register: keyscan
#    failed_when: keyscan.rc != 0 or keyscan.stdout == ''
#    changed_when: False
#    when: keygen.rc == 1

#  - name: add ssh-key to local known_hosts
#    local_action: 
#      module: lineinfile
#      name: ~/.ssh/known_hosts
#      create: yes
#      line: "{{ item }}"
#    when: keygen.rc == 1
#    with_items: '{{ keyscan.stdout_lines|default([]) }}'

  - name: Patch OS
    yum:
      name: '*'
      state: latest

  - name: Add extra packages
    yum:
      name: '{{ item }}'
      state: installed
    with_items:
      - open-vm-tools
      - chrony
      - perl
      - net-tools
      - wget
      - git
      - bind-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - libsemanage-python

  - name: Check for time Server
    check_mode: no
    shell: grep "central.cavenet.ca iburst" /etc/chrony.conf
    changed_when: false
    ignore_errors: true
    register: time_server
    failed_when: time_server.rc >= 2

  - name: insert Time Source
    lineinfile:
      path: /etc/chrony.conf
      insertafter: 'server 3\.centos\.pool\.ntp\.org iburst'
      line: 'server central.cavenet.ca iburst'
      state: present
    when: time_server.rc == 1

  - name: delete centos time sources
    lineinfile:
      path: /etc/chrony.conf
      regexp: 'centos\.pool\.ntp\.org'
      state: absent

  - name: Restart chronyd
    service:
      name: chronyd
      state: restarted
      enabled: yes

  - name: Add public key to provisioned accounts
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '/home/jkelly/.ssh/id_djk_rsa.pub' ) }}"
    with_items:
      - root
      - jkelly

  - name: enable nfs writing in SELinux
    seboolean:
      name: virt_use_nfs
      state: yes
      persistent: yes

  - name: push sudoers from localhost
    copy:
      src: sudoers
      dest: /etc/sudoers
      owner: root
      group: root
      mode: '0400'
      validate: visudo -cf %s

  - name: copy audit filter to host
    copy:
      src: test-audit-policy.yaml
      dest: /usr/local/etc/test-audit-policy.yaml
      owner: root
      group: root
      mode: '0644'

  - name: Reboot Server
    shell: shutdown -r +1

  - name: Hold for Reboot
    wait_for_connection:
      timeout: 900
      delay: 120
      sleep: 5

  - debug: 
      msg: "back after Reboot."
